[theme]
primaryColor = "#FF571F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#1A1A1A"
font = "sans serif"

[server]
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false 